context("General TODO of the package")

test_that(desc="TODO",{
  skip("just a todo")
  expect_true(FALSE, info = "Fix manual calculated tests for mi, imi, goup_imi and group mi")
  expect_true(FALSE, info = "fix sample_types_given_topic example")
  expect_true(FALSE, info = "fix vanilla LDA vignette - remove janeausten dependency")
  expect_true(FALSE, info = "fix examples everywhere")
  expect_true(FALSE, info = "check out of array potential error in sampler - R. This is the only potential for out of array errors")
  expect_true(FALSE, info = "fix all TODO in documentation")
  expect_true(FALSE, info = "fix prior in topic_entropy")
  expect_true(FALSE, info = "Add more 'real' tests on calculating relevance and term-score - manually calculated values")
  expect_true(FALSE, info = "Fix references and documentation in top terms")
  expect_true(FALSE, info = "Fix introduction tutorial")
  expect_true(FALSE, info = "Check if overwriting is faster")
  expect_true(FALSE, info = "E-mail Max, Niklas, Mattias and David")
  expect_true(FALSE, info = "Cleanup API - a more tidy API for bayesian checking - one argument - data in tidy format. Everything should spit out tidy formats")
})
