# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' rcategorical
#' @description
#' Sample a categorical variable from
#'
#' @param p a vector of (pssoble unnormalized) probabilities.
#'
rcategorical <- function(p) {
    .Call('tidytopics_rcategorical', PACKAGE = 'tidytopics', p)
}

#' @title
#' Sample vanilla LDA
#'
#' @description
#' Sample a couple of iterations using simple LDA
#'
#' @param p a vector of (pssoble unnormalized) probabilities.
#'
#' @export
sample_vanilla_lda <- function(doc, type, z, K, D, V, iter, beta, alpha) {
    .Call('tidytopics_sample_vanilla_lda', PACKAGE = 'tidytopics', doc, type, z, K, D, V, iter, beta, alpha)
}

